title: "UEP-0239: Geospatial Programming with Python"
author: Uku-Kaspar Uustalu
copyright: "2021"
logo: logo.png

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - linkify
    - replacements
    - substitution
  myst_substitutions:
    canvas_url: https://canvas.tufts.edu/courses/27438
    piazza_url: https://piazza.com/tufts/spring2021/uep239/resources
    canvas_link: "{{ '[Canvas]({})'.format(canvas_url) }}"
    piazza_link: "{{ '[Piazza]({})'.format(piazza_url) }}"

repository:
  url: https://github.com/uep239/uep239.github.io
  path_to_book: source
  branch: main

html:
  baseurl: https://uep239.github.io/
  google_analytics_id: UA-188456160-2
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: false
  extra_navbar: ""

sphinx:
  config:
    html_last_updated_fmt: "%b %d, %Y"